### ISSUE TITLE
Re-Design

### ISSUE THREAD

**Issue by LarissaAbreu** [valleweb/valle-card#22]
Re-design with a button minimize and resize behavior.

![Screen Shot 2019-06-25 at 19 18 55](https://user-images.githubusercontent.com/16037749/60137705-22fa1900-977e-11e9-8726-8eb756c05ea9.png)

**Comment by LarissaAbreu** [comment]
@afonsopacifer review pls

**Comment by afonsopacifer** [comment]
@LarissaAbreu  :shipit:
