### ISSUE TITLE
User API

### ISSUE THREAD

**Issue by LarissaAbreu** [valleweb/valle-card#23]
Basta usar a tag `valle-card`, que aceita o atributo `minimize` caso o card possa ser minimizado, e inserir o conteúdo desejado dentro da mesma. Por exemplo:

```html
<valle-card minimize>
  <h1>Título do card</h1>
  <p>Conteúdo do card</p>
</valle-card>
```

**Comment by LarissaAbreu** [comment]
@afonsopacifer review pls

**Comment by afonsopacifer** [comment]
:shipit:
